version: "3"
services:
  nginx-chan:
    image: weseek/nginx-nchan
    ports:
      - 8080:80
    volumes:
      - ./config/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - nginx-chan-net
  
networks:
  nginx-chan-net: 
    driver: bridge